name: PiMobile
options:
  bundleIdPrefix: com.pimobile
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.4"
  generateEmptyDirectories: true
  groupSortPosition: top

targets:
  PiApp:
    type: application
    platform: iOS
    sources:
      - path: PiApp/PiApp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: PiApp/PiApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.pimobile.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) DEBUG"
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
    resources:
      - path: ../shared/model-catalogue.json
      - path: ../shared/system-prompt.txt
